excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://hiralove.github.io
title: A Rusty Coder
email: hiralove@gmail.com
author: Jaspal Singh
description: Hey there, My name is Jaspal, and I am from Jaipur, India. I love to blog, and I write on a variety of topics. I love gadgets & exploring new places. Movies make me energetic & Music keeps me going.
paginate: 3
google_analytics: 
theme: jekyll-theme-cayman